### PR TITLE
Fix: Normalize macro route path to ensure compatibility with Windows

### LINKED ISSUE #10: Static serving broken in Windows
Hello,

This seems like a great crate! I would prefer to use it over rust-embed and memory-serve, yet, it seems serving paths in Windows is broken.

```
thread 'tokio-runtime-worker' (8388) panicked at C:\Users\Markus\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\static-serve-0.5.0\src\lib.rs:93:12:
Paths must start with a `/`
```

Best, Markus

### PR DESCRIPTION
**Pull request by bartleboeuf**
Issue description : 
The macro was generating route paths from filesystem paths without normalizing separators/leading slash on Windows, so Axum received paths like \foo and panicked.

Fixes : 
- Updated EmbeddedFileInfo path handling to always normalize generated web routes via a helper.
- In route generation, relative paths are now converted to web-safe paths (backslashes --> /, ensure leading /) .
- strip_html_ext logic was working on absolute/path-string prefixes, which broke on Windows separator differences and could generate wrong routes. A quick rework of the helper is done. 

All Unit tests are now good on Linux and Windows. (i was not able to test on Mac).

### CODE REVIEW

**Comment by bartleboeuf** [comment]
#10

File: static-serve-macro/src/lib.rs [hunk 1]
```diff
@@ -820,21 +820,48 @@ fn etag(contents: &[u8]) -> String {
...
+    output
+}
+
+/// Normalize an embedded asset's relative file path into a web route path.
+///
+/// - Converts Windows `\` path separators to `/`.
+/// - Ensures the returned path starts with `/`.
+/// - Returns `/` for the empty path (used for `index.html` when `strip_html_ext = true`).
+fn normalize_web_path(relative_path: &str) -> String {
+    let normalized = relative_path.replace('\\', "/");
```
Comment (pacman82) [inline static-serve-macro/src/lib.rs]: Does it make sense to only execute this part on windows platforms? It's an edge case of course, but `\` is a valid character in linux file or directory names.

Comment (paolobarbolini) [reply static-serve-macro/src/lib.rs]: What about parsing the path using [`Path::components`](https://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.components)? If this works correctly, it'd remove the edge-case on our side and let the stdlib deal with it.

Comment (pacman82) [reply static-serve-macro/src/lib.rs]: Even better!

Comment (bartleboeuf) [reply static-serve-macro/src/lib.rs]: Path component is now used in replacement of the simple character replacement

File: static-serve-macro/src/lib.rs [hunk 2]
```diff
@@ -820,21 +820,60 @@ fn etag(contents: &[u8]) -> String {
...
+/// Path segments are normalized via `Path::components()`. The returned
+/// route is always absolute (starts with `/`) and defaults to `/` for
+/// empty input.
+fn normalize_web_path(relative_path: &str) -> String {
+    let normalized = Path::new(relative_path)
+        .components()
+        .filter_map(|component| match component {
+            std::path::Component::Normal(segment) => segment.to_str(),
+            std::path::Component::CurDir => Some("."),
+            std::path::Component::ParentDir => Some(".."),
```
Comment (paolobarbolini) [inline static-serve-macro/src/lib.rs]: I'm not sure what we should do with these, they are not something I'd expect to be in the URL.

File: static-serve-macro/src/lib.rs [hunk 3]
```diff
@@ -820,21 +820,60 @@ fn etag(contents: &[u8]) -> String {
...
+            std::path::Component::RootDir | std::path::Component::Prefix(_) => None,
+        })
+        .collect::<Vec<_>>()
+        .join("/");
+    if normalized.is_empty() {
+        "/".to_owned()
+    } else {
+        format!("/{normalized}")
+    }
```
Comment (paolobarbolini) [inline static-serve-macro/src/lib.rs]: It could be simplified to this:

```suggestion
    format!("/{normalized}")
```

File: static-serve-macro/src/lib.rs [hunk 4]
```diff
@@ -820,21 +820,60 @@ fn etag(contents: &[u8]) -> String {
...
+        output = prefix.to_owned();
     }
 
     // If it was `/index.html` or `/index.htm`, also remove `index`
     if output.ends_with("/index") {
-        output = output.strip_suffix("index").unwrap_or("/");
+        output = output.strip_suffix("index").unwrap_or("/").to_owned();
+    } else if output == "index" {
+        output.clear();
     }
```
Comment (paolobarbolini) [inline static-serve-macro/src/lib.rs:853]: Why would we have just `index`?

File: static-serve-macro/src/lib.rs (hunk 2 above)
Comment (bartleboeuf) [reply static-serve-macro/src/lib.rs]: For normal asset embedding, it's a bit overkill. It's more useful for having a defensive measure in case of arbitrary inputs if the method is used directly outside the main embedded process.

File: static-serve-macro/src/lib.rs (hunk 4 above)
Comment (bartleboeuf) [reply static-serve-macro/src/lib.rs:853]: if strip_html_ext is enabled and you want to remove this part then, root index.html will map to "/index" instead of "/". I notice this with the "strips_html_correctly" test, which failed.

**Comment by pacman82** [comment]
Anything I could help with to move this forward?

**Review by paolobarbolini — APPROVED** [review]
Sorry for the delay. A few more improvement ideas around this area of the code came up while reviewing this PR, put we won't make you wait for those to land first. LGTM.

**Comment by pacman82** [comment]
@paolobarbolini No need to apologize. Thanks for the great work. Looking forward to the release and the other improvements. 🎉
